### ISSUE TITLE
Explain what Trace Restart Button does

### ISSUE THREAD

**Issue by mishakogan** [relativitydev/relativity-trace-documentation#102]
and what are the ramifications of this action: e.g. Data Batches in progress might get "Thread aborted Error" and might need to be restarted

**Comment by DigitalSaucePro** [comment]
The ramification is during the Agent Restart, all threads for all workspaces will be aborted.  Any work in progress will throw this error.  For data batches specifically, they will be marked with Completed With Errors and will be available for retry.

**Comment by mishakogan** [comment]
@DigitalSaucePro - please update relevant documentation with this information.

**Comment by peterhallerREL** [comment]
Done
