### ISSUE TITLE
Link to image broken on AI Extracted Text Cleansing page

### ISSUE THREAD

**Issue by atien23** [relativitydev/relativity-trace-documentation#263]
https://relativitydev.github.io/relativity-trace-documentation/docs/administrator_guide/enrichment/data_transforms.html#ai-extracted-text-cleansing-data-transformation

This needs to be fixed ASAP as I have to send the documentation out to various clients since we are turning on this feature for them.

**Comment by peterhallerREL** [comment]
Resolved with full update to that section of documentation. @atien23
