### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by KirstenLRel** [relativitydev/relativity-trace-documentation#278]
On the Creating a Policy page (https://relativitydev.github.io/relativity-trace-documentation/docs/user_guide/alerting/creating_a_policy.html), the images are missing. This applies to section 1-Creating a Policy, 2-Customizing and Running a Rule, and 3-Validating Results. See attached image for example.

![image](https://user-images.githubusercontent.com/91224671/141200235-8c505916-e9b6-4605-bd81-628213679df5.png)

**Comment by daccetta2** [comment]
Resolved with a previous issue

**Comment by daccetta2** [comment]
Close
