### ISSUE TITLE
Mark "logging" within Setup as deprecated 

### ISSUE THREAD

**Issue by peterhallerREL** [relativitydev/relativity-trace-documentation#285]
This functionality is no longer supported even though it has not yet been removed from the product. Please mark it as deprecated so users understand it's not something necessary for them to use.

**Comment by daccetta2** [comment]
@peterhallerREL -> there are two pages under Setup that mention logging, do you mean **Getting Started** or **System Health**?

**Comment by peterhallerREL** [comment]
"Adjusting Logging Level" on the System Health page @daccetta2

**Comment by daccetta2** [comment]
Created a PR to resolve this
