### ISSUE TITLE
Deprecate Trace Exchange data source

### ISSUE THREAD

**Issue by peterhallerREL** [relativitydev/relativity-trace-documentation#299]
This data sources delivered by Trace should no longer be used.

**Comment by daccetta2** [comment]
@peterhallerREL -> Microsoft Exchange Data Source is already marked as Deprecated under Admin Guide. Is the goal of this ticket to mark it in User Guide as well?

https://relativitydev.github.io/relativity-trace-documentation/docs/user_guide/data_sources.html

**Comment by peterhallerREL** [comment]
Nope. It just needs to be marked where it is in the Admin Guide. I've closed this as done.
