### ISSUE TITLE
Connect Viewer work to Text Cleaning Data Transformation

### ISSUE THREAD

**Issue by daccetta2** [relativitydev/relativity-trace-documentation#352]
https://relativitydev.github.io/relativity-trace-documentation/docs/administrator_guide/enrichment/data_transforms.html#ai-extracted-text-cleansing-data-transformation

https://relativitydev.github.io/relativity-trace-documentation/docs/user_guide/review/reviewing_communications.html

**Comment by peterhallerREL** [comment]
Completed.
