### ISSUE TITLE
Update data batch in proactive ingestion API missing loadfile path

### ISSUE THREAD

**Issue by MGibson1** [relativitydev/relativity-trace-documentation#48]
Need to update the PUT statement body to include Load File Path field like this:

{
  "Status": {
    "Guids": [
      "32452D3D-35D2-4FF5-92E6-1DD01D755482"
    ],
    "Artifact Type Name": "Choice"
  },
  "Load File Path": "DataTransfer\\Import\\Trace BIST Provider\\1041141\\1041337_ready\\loadfile.dedup.updates.dat",
  "DocumentCount_LoadFileGenerated": "500",
  "Timestamp_LoadFileGenerated": "3\/27\/2018 4:15:13 PM",
  "Parent Artifact": {
    "Artifact ID": 1003663
  },
  "Artifact Type Name": "Data Batch",
  "Artifact ID": 1044380
}

**Comment by MGibson1** [comment]
@mishakogan

**Comment by mishakogan** [comment]
Resolved
