### ISSUE TITLE
Remove mention of IPI and replace TPI for Trace Proactive Ingestion

### ISSUE THREAD

**Issue by mishakogan** [relativitydev/relativity-trace-documentation#70]
ref: https://relativitydev.github.io/relativity-trace-documentation/proactive_ingestion_api_documentation

**Comment by daccetta2** [comment]
@mishakogan - I resolved this so I am going to close this. Link is below

https://relativitydev.github.io/relativity-trace-documentation/docs/administrator_guide/proactive_ingestion_api_documentation.html#ingest-data-from-custom-data-sources
