### ISSUE TITLE
Add minimum permissions needed for Trace Shipper 

### ISSUE THREAD

**Issue by mishakogan** [relativitydev/relativity-trace-documentation#71]
Similar to how it is done for Staging Explorer https://help.relativity.com/RelativityOne/Content/Relativity/RelativityOne_Staging_Explorer/RelativityOne_Staging_Explorer.htm#Staging

**Comment by peterhallerREL** [comment]
@akorczynskikcura Misha added this a while back. Can you check our documentation to make sure this is clear and submit a PR if it needs to be added?
