### ISSUE TITLE
Validate if all roles for exchange are absolutely needed

### ISSUE THREAD

**Issue by mishakogan** [relativitydev/relativity-trace-documentation#89]
I think only `ApplicationImpersonation` is needed and NOT `ImportExport` OR `LegalHold`

**Comment by peterhallerREL** [comment]
@akorczynskikcura can you confirm what is actually needed here for our Trace Exchange Data Source (data retrieval). I know eventually we are going to move customers over to Collect, but if we know the answer to this we might as well update it.

https://relativitydev.github.io/relativity-trace-documentation/user_documentation#microsoft-exchange-data-source
